### ISSUE TITLE
使用插件上传图片，默认生成的链接画质会压缩

### ISSUE THREAD

**Issue by zzkuner** [Redns/picgo-plugin-postimage#2]
https://i.postimg.cc/xxxxx?dl=1

这个dl=1的作用是什么呢。怎么修改呢

**Comment by Redns** [comment]
感谢反馈，该问题已修复，请将插件更新至最新版本（v1.1.2+）

**Comment by Redns** [comment]
关于 `dl=1` 的问题，因为 [Postimages](https://postimages.org/) 并没有公布图片上传、源链接获取等接口，因此本插件所有接口均是通过抓包等方式间接获取的，所以我也无法解释该参数的具体含义哈

**Comment by zzkuner** [comment]
收到，谢谢谢谢




张泽坤
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Redns/picgo-plugin-postimage"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月27日(星期四) 下午2:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Redns/picgo-plugin-postimage] 使用插件上传图片，默认生成的链接画质会压缩 (Issue #2)





 
感谢反馈，该问题已修复，请将插件更新至最新版本（v1.1.2+）

**Comment by wzaiz** [comment]
可以在``i.postimg.cc``前加入``i0.wp.com/``（或``i1``，``i2``），也可加入``2img.net/h/``，具体形式为``https://i0.wp.com/i.postimg.cc/xxxxx``或``https://2img.net/h/i.postimg.cc/xxxxx``

``dl=1``应该是下载参数，加上``dl=1``，粘贴到浏览器就会自动下载而不是加载图片
