### ISSUE TITLE
不支持 PicGo 中的「上传前重命名」设置

### ISSUE THREAD

**Issue by Tseing** [Redns/picgo-plugin-postimage#3]
![PicGo_KlBn9wmr92](https://github.com/Redns/picgo-plugin-postimage/assets/45302927/331e3595-3892-40ff-a828-1b95c245384d)
![A6s4mZrvDD](https://github.com/Redns/picgo-plugin-postimage/assets/45302927/a7e46e02-2c46-458a-a4a1-3a69a4aafde7)

如上图所示，就算手动修改了文件名，生成链接中的文件名也没有改变。这导致无法使用自动哈希编码命名等插件，请问是否有解决方法呢？

**Comment by Redns** [comment]
问题已修复，将插件更新至 `v1.1.4+` 即可
